train:
	python train_dqn_agent.py \
		--config-file configs/default.yaml \
		--frame-size 84 84 \
		--stack-size 4 \
		--learning-rate 0.0001 \
		--mem-capacity 1000000 \
		--model-name second_model \
		--num-train-steps 10000 \
		--discount-factor 0.2
