obstacles: [
        ["objects_examples/obstacle_1.png", 0.2, 0.5, 0],
        ["objects_examples/obstacle_2.png", 0.2, 0.5, 0],
        ["objects_examples/obstacle_3.png", 0.2, 0.5, 0],
        ["objects_examples/new_object.png", 0.2, 0.5, 0],
    ]
obstacles_speed: 2
background: [25, 100, 89]
agent_size: 8
agent_color: [0, 0, 255]
test_steps: 10000
